self.addEventListener("install",e=>{
  e.waitUntil(
    caches.open("itasset").then(c=>
      c.addAll([
        "index.html",
        "dashboard.html",
        "admin.html",
        "config.js"
      ])
    )
  );
});
self.addEventListener("fetch",e=>{
  e.respondWith(
    caches.match(e.request).then(r=>r||fetch(e.request))
  );
});
